import type { StationDef } from "@/lib/types";

/**
 * 's-Hertogenbosch — one pedestrian tunnel running from the City center side
 * (top of the map) to Paleiskwartier (bottom). Tracks 1, 3, 4, 6 and 7 cross
 * it; the a/b halves of each platform sit left and right of the tunnel.
 *
 * Geometry is expressed against a 402 x 620 canvas that StationMap scales to fit.
 */
export const denBosch: StationDef = {
  slug: "denbosch",
  name: "'s-Hertogenbosch",
  kicker: { en: "TRAIN STATION", nl: "TREINSTATION" },
  ends: {
    top: { en: "CITY CENTER", nl: "CENTRUM" },
    bottom: { en: "PALEISKWARTIER", nl: "PALEISKWARTIER" },
  },
  noEscalator: { en: "NO ESCALATOR", nl: "GEEN ROLTRAP" },
  noEscalatorBox: { left: 86, top: 142, width: 62, height: 52 },

  rails: [{ top: 207 }, { top: 262 }, { top: 347 }, { top: 402 }, { top: 487 }],
  plates: [{ top: 137 }, { top: 277 }, { top: 417 }],
  trackLabels: [
    { side: "l", top: 202, text: "1a" },
    { side: "r", top: 202, text: "1b" },
    { side: "l", top: 257, text: "3a" },
    { side: "r", top: 257, text: "3b" },
    { side: "l", top: 342, text: "4a" },
    { side: "r", top: 342, text: "4b" },
    { side: "l", top: 397, text: "6a" },
    { side: "r", top: 397, text: "6b" },
    { side: "l", top: 482, text: "7" },
    { side: "r", top: 482, text: "7" },
  ],

  units: [
    {
      id: "F1",
      type: "escalator",
      glyph: "▼",
      name: { en: "Front entrance · up", nl: "Voorzijde · omhoog" },
      sub: { en: "Stationsplein → tunnel", nl: "Stationsplein → tunnel" },
      box: { left: 170, top: 38, width: 26, height: 56 },
    },
    {
      id: "F2",
      type: "escalator",
      glyph: "▲",
      name: { en: "Front entrance · down", nl: "Voorzijde · omlaag" },
      sub: { en: "Tunnel → Stationsplein", nl: "Tunnel → Stationsplein" },
      box: { left: 204, top: 38, width: 26, height: 56 },
    },
    {
      id: "L1",
      type: "lift",
      name: { en: "Front entrance lift", nl: "Lift voorzijde" },
      sub: { en: "Stationsplein ↔ tunnel", nl: "Stationsplein ↔ tunnel" },
      box: { left: 252, top: 49, width: 34, height: 34 },
    },
    {
      id: "E1",
      type: "escalator",
      glyph: "◀",
      name: { en: "Track 1b · up", nl: "Spoor 1b · omhoog" },
      sub: { en: "Platform 1b → tunnel", nl: "Perron 1b → tunnel" },
      box: { left: 254, top: 142, width: 62, height: 22 },
    },
    {
      id: "E2",
      type: "escalator",
      glyph: "▶",
      name: { en: "Track 1b · down", nl: "Spoor 1b · omlaag" },
      sub: { en: "Tunnel → platform 1b", nl: "Tunnel → perron 1b" },
      box: { left: 254, top: 172, width: 62, height: 22 },
    },
    {
      id: "L2",
      type: "lift",
      name: { en: "Platform 1 lift", nl: "Lift perron 1" },
      sub: { en: "Tunnel ↔ platform 1a / 1b", nl: "Tunnel ↔ perron 1a / 1b" },
      box: { left: 44, top: 151, width: 34, height: 34 },
    },
    {
      id: "E3",
      type: "escalator",
      glyph: "▶",
      name: { en: "Track 3a · 4a · up", nl: "Spoor 3a · 4a · omhoog" },
      sub: { en: "Platform 3a / 4a → tunnel", nl: "Perron 3a / 4a → tunnel" },
      box: { left: 86, top: 312, width: 62, height: 22 },
    },
    {
      id: "E4",
      type: "escalator",
      glyph: "◀",
      name: { en: "Track 3a · 4a · down", nl: "Spoor 3a · 4a · omlaag" },
      sub: { en: "Tunnel → platform 3a / 4a", nl: "Tunnel → perron 3a / 4a" },
      box: { left: 86, top: 282, width: 62, height: 22 },
    },
    {
      id: "E5",
      type: "escalator",
      glyph: "◀",
      name: { en: "Track 3b · 4b · up", nl: "Spoor 3b · 4b · omhoog" },
      sub: { en: "Platform 3b / 4b → tunnel", nl: "Perron 3b / 4b → tunnel" },
      box: { left: 254, top: 282, width: 62, height: 22 },
    },
    {
      id: "E6",
      type: "escalator",
      glyph: "▶",
      name: { en: "Track 3b · 4b · down", nl: "Spoor 3b · 4b · omlaag" },
      sub: { en: "Tunnel → platform 3b / 4b", nl: "Tunnel → perron 3b / 4b" },
      box: { left: 254, top: 312, width: 62, height: 22 },
    },
    {
      id: "L3",
      type: "lift",
      name: { en: "Platform 3 · 4 lift", nl: "Lift perron 3 · 4" },
      sub: { en: "Tunnel ↔ platform 3 / 4", nl: "Tunnel ↔ perron 3 / 4" },
      box: { left: 44, top: 291, width: 34, height: 34 },
    },
    {
      id: "E7",
      type: "escalator",
      glyph: "▶",
      name: { en: "Track 6a · 7 · up", nl: "Spoor 6a · 7 · omhoog" },
      sub: { en: "Platform 6a / 7 → tunnel", nl: "Perron 6a / 7 → tunnel" },
      box: { left: 86, top: 452, width: 62, height: 22 },
    },
    {
      id: "E8",
      type: "escalator",
      glyph: "◀",
      name: { en: "Track 6a · 7 · down", nl: "Spoor 6a · 7 · omlaag" },
      sub: { en: "Tunnel → platform 6a / 7", nl: "Tunnel → perron 6a / 7" },
      box: { left: 86, top: 422, width: 62, height: 22 },
    },
    {
      id: "E9",
      type: "escalator",
      glyph: "◀",
      name: { en: "Track 6b · 7 · up", nl: "Spoor 6b · 7 · omhoog" },
      sub: { en: "Platform 6b / 7 → tunnel", nl: "Perron 6b / 7 → tunnel" },
      box: { left: 254, top: 422, width: 62, height: 22 },
    },
    {
      id: "E10",
      type: "escalator",
      glyph: "▶",
      name: { en: "Track 6b · 7 · down", nl: "Spoor 6b · 7 · omlaag" },
      sub: { en: "Tunnel → platform 6b / 7", nl: "Tunnel → perron 6b / 7" },
      box: { left: 254, top: 452, width: 62, height: 22 },
    },
    {
      id: "L4",
      type: "lift",
      name: { en: "Platform 6 · 7 lift", nl: "Lift perron 6 · 7" },
      sub: { en: "Tunnel ↔ platform 6 / 7", nl: "Tunnel ↔ perron 6 / 7" },
      box: { left: 340, top: 431, width: 34, height: 34 },
    },
    {
      id: "B1",
      type: "escalator",
      glyph: "▲",
      name: { en: "Back entrance · up", nl: "Achterzijde · omhoog" },
      sub: { en: "Parallelweg → tunnel", nl: "Parallelweg → tunnel" },
      box: { left: 204, top: 522, width: 26, height: 56 },
    },
    {
      id: "B2",
      type: "escalator",
      glyph: "▼",
      name: { en: "Back entrance · down", nl: "Achterzijde · omlaag" },
      sub: { en: "Tunnel → Parallelweg", nl: "Tunnel → Parallelweg" },
      box: { left: 170, top: 522, width: 26, height: 56 },
    },
    {
      id: "L5",
      type: "lift",
      name: { en: "Back entrance lift", nl: "Lift achterzijde" },
      sub: { en: "Tunnel ↔ Parallelweg", nl: "Tunnel ↔ Parallelweg" },
      box: { left: 252, top: 533, width: 34, height: 34 },
    },
  ],
};
